# Generated by Django 4.1.7 on 2023-03-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidauth', '0005_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='RideHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('status', models.CharField(default='started', max_length=255)),
                ('fare', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_doc', models.ImageField(upload_to='documents/')),
                ('pancard_doc', models.ImageField(upload_to='documents/')),
                ('license_doc', models.ImageField(upload_to='documents/')),
                ('rc_doc', models.ImageField(upload_to='documents/')),
                ('insurance_doc', models.ImageField(upload_to='documents/')),
                ('status', models.CharField(default='open', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('driver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ManyToManyField(to='raidauth.vehicletype')),
            ],
        ),
    ]
