# Generated by Django 4.1.7 on 2023-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidauth', '0006_alter_vehicletype_vehicle_image_ridehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentslist',
            name='voter_doc',
            field=models.ImageField(default='null', upload_to='documents/'),
        ),
    ]
