# Generated by Django 4.1.7 on 2023-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidauth', '0007_documentslist_voter_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentslist',
            name='aadhar_doc',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentslist',
            name='insurance_doc',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentslist',
            name='license_doc',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentslist',
            name='pancard_doc',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentslist',
            name='rc_doc',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentslist',
            name='voter_doc',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
    ]
