# Generated by Django 4.1.7 on 2023-03-19 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidauth', '0009_alter_documentslist_aadhar_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentslist',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentslist',
            name='vehicle_type',
            field=models.ManyToManyField(blank=True, null=True, to='raidauth.vehicletype'),
        ),
    ]
